using System;
using System.Diagnostics;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace NetModel.CodeGen;

[Generator]
public class ProtocolGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		Debug.WriteLine("Running");

		var protocols = context.SyntaxProvider.CreateSyntaxProvider(
			predicate: static (syntaxNode, _) =>
				syntaxNode is InterfaceDeclarationSyntax iDecl &&
				iDecl.AttributeLists
					.SelectMany(attrList => attrList.Attributes)
					.Any(),
			transform: static (ctx, _) =>
				ctx.Node is InterfaceDeclarationSyntax iDecl &&
				ctx.SemanticModel.GetDeclaredSymbol(iDecl) is ISymbol symbol &&
				ctx.SemanticModel.Compilation.GetTypeByMetadataName("NetModel.ProtocolAttribute") is INamedTypeSymbol attr &&
				symbol.GetAttributes().Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attr)) ?
				symbol : null
		).Where(static p => p is not null);

		context.RegisterSourceOutput(protocols, static (spc, symbol) =>
		{
			var ns = symbol.ContainingNamespace.ToDisplayString();
			var name = symbol.Name;
			var sb = new StringBuilder();
			sb.AppendLine("// <auto-generated>");
			sb.AppendLine("using System;");
			sb.AppendLine($"namespace {ns};");
			sb.AppendLine($"partial interface {name}{{");
			sb.AppendLine("public static void Test(){");
			sb.AppendLine("Console.WriteLine(\"Test\");");
			sb.AppendLine("}");
			sb.AppendLine("}");

			spc.AddSource($"{name}Extensions.Incremental.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
		});
	}
}
